# Generated by Django 2.2.5 on 2019-09-30 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 5, 12, 28, 136018, tzinfo=utc)),
        ),
    ]
