# Generated by Django 2.2.5 on 2019-09-30 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0003_auto_20190930_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 5, 38, 45, 697642, tzinfo=utc)),
        ),
    ]
